import "./globals.css";
import Web3Provider from "@/provider/Web3Provider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Web3Provider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Web3Provider>
  );
}
